### ISSUE TITLE
How to use on workspace?

### ISSUE THREAD

**Issue by richarddd** [itmettkeDE/cargo-patch#64]
I have a workspace consisting of two sub packages a,b:

```toml
[workspace]
resolver = "2"
members = ["a", "b"]
```

In `a` is a dependency i want to patch. I also prefer to use a build.rs script

**Comment by mettke** [comment]
Hey @richarddd,

this functionality is shown in this test:

https://github.com/itmettkeDE/cargo-patch/blob/master/tests/patch_crates_io.rs#L195

Basically, the `package.metadata.patch` part belongs into the Cargo.toml of the workspace. Same goes for the `[patch.crates-io]` part. The Cargo.toml of the member must not be changed.

Not, however, that this patches the crate for all workspace members. It is not possible to patch a given dependency only for one crate. If you need a functionality like this, then it should be possible to add the dependency with a custom name and only patching that using:

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#renaming-dependencies-in-cargotoml

**Comment by jabir366** [comment]
Hi @mettke in my case it is a bit different , I want to patch a package inside a workspace ,but the workspace itselft is a dependecy to my project 

I am trying to patch `heim-host` which is a package inside workspace `heim` and I  `heim` is a dependency of `vector` .
In this case how can I apply the patch? 
I have 
```
package.metadata.patch.heim.heim-host
version = "1.0"
patches = ["heim.patch"]
```
But, only heim is downloaded to `target/patch` not the  depedent packages, Thanks!

**Comment by mettke** [comment]
Hey @jabir366,

yes your situation is in fact different. This is how you have to do it:

First you need to add  `heim-host` as a direct dependency to `Vector`. Otherwise you will not be able to patch it. Once its patched like this, `Helm` will also use the patched version.

```
[dependencies]
helm-host = { version = "*" }
```
Afterwards you can change the metadata part to this:

```
[package.metadata.patch.heim-host]
version = "1.0"
patches = ["heim.patch"]
```

Now you can add the patch entry;

```
[patch.crates-io]
helm-host = { path = './target/patch/helm-host-x.x.x' }
```

Once you compile you will notice that `helm` is using the patched dependency.

**Comment by jabir366** [comment]
hi @mettke , unfortunately , it did not work for me.
I added the following in my Vector `Cargo.toml`
```
[dependencies]
heim-host = { version = "*"}

[patch.crates-io]
heim-host = { path = "./target/patch/heim-host-0.1.0-rc.1" }

[package.metadata.patch.heim-host]
patches = [ "heim.patch" ]
version = "1.0"
```
When I was doing the `cargo patch` I was getting the following error
```
[root@machine1 vector]# cargo patch
Error: failed to select a version for the requirement `platforms = "^0.2.0"`
candidate versions found which didn't match: 3.4.0, 3.3.0, 3.2.0, ...
location searched: crates.io index
required by package `heim-host v0.0.1`
    ... which satisfies dependency `heim-host = "*"` of package `vector v0.36.0 (/root/megha_old/jab/vector)`
perhaps a crate was updated and forgotten to be re-vendored?
```

Later, I changed the heim-host version from `*` to `0.1.0-rc.1`

now the error got changed to even more complex dependency issue
```
vector]# cargo patch
Error: failed to select a version for `platforms`.
    ... required by package `heim-host v0.1.0-rc.1`
    ... which satisfies dependency `heim-host = "^0.1.0-rc.1"` of package `vector v0.36.0 (/root/megha_old/jab/vector)`
versions that meet the requirements `~1.0` are: 1.0.3, 1.0.2

all possible versions conflict with previously selected packages.

  previously selected package `platforms v1.1.0`
    ... which satisfies dependency `platforms = "^1.1"` (locked to 1.1.0) of package `heim-host v0.1.0-rc.1 (https://github.com/vectordotdev/heim.git?branch=update-nix#a66c4407)`
    ... which satisfies git dependency `heim-host` (locked to 0.1.0-rc.1) of package `heim v0.1.0-rc.1 (https://github.com/vectordotdev/heim.git?branch=update-nix#a66c4407)`
    ... which satisfies git dependency `heim` (locked to 0.1.0-rc.1) of package `vector v0.36.0 (/root/megha_old/jab/vector)`

failed to select a version for `platforms` which could resolve this conflict
```
* I later tried changing `platforms` version in heim-host to see any changes are happening. nothing happened except these two errors. Thanks.

**Comment by mettke** [comment]
hm... would you mind giving me a full Cargo.toml file so that I can investigate. At the moment its a bit hard for me to understand where the problem might be.

**Comment by richarddd** [comment]
> package.metadata.patch

In my case that wont work since my root workspace does not contain a [package] definition.

```toml
[workspace]
resolver = "2"
members = ["a", "b"]

[package.metadata.patch.serde] #<--- this here wont work
version = "*"
patches = ["patches/promise-poll.patch"]
```

**Comment by jabir366** [comment]
hi @mettke, you can refer [this one](https://github.com/vectordotdev/vector/blob/master/Cargo.toml),  if you want to re-produce the changes, try to apply patch to  heim-host, which is a dependency for vector, thanks

**Comment by mettke** [comment]
@richarddd 

Ok now I understand your problem. This is how to solve it:

The workspace toml needs to look like this:
```toml
[workspace]
members = ["test_pkg1", "test_pkg2"]
resolver = "2"

[patch.crates-io]
serde = { path = "./target/patch/serde-1.0.203" }
```

The package toml has to look like this:

```toml
[package]
name = "test_pkg1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.203"

[package.metadata.patch.serde]
version = "1.0.203"
patches = []
```

And then you can use cargo patch to patch it. 

Using a build.rs works similar, by using the following toml for the package:
```toml
[package]
name = "test_pkg1"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.203"

[package.metadata.patch.serde]
version = "1.0.203"
patches = []

[build-dependencies]
cargo-patch = "0.3"
```
